### ISSUE TITLE
use `site.github.source.branch` instead of `site.branch`?

### ISSUE THREAD

**Issue by deargle** [benbalter/retlab#26]
https://github.com/benbalter/retlab/blob/d4ddd56032fe4f92494d09e03db05c483fdd62e5/_layouts/post.html#L13 relies on `site.branch`, which (1) isn't set in the layout _config.yml, and (2) could possibly be swapped out for `site.github.source.branch`? Opposed?

**Comment by benbalter** [comment]
Good call @deargle. I'd be glad to merge a PR to make that change if you submit one.
