### ISSUE TITLE
/assets/img/header.jpg is not displayed on GitHub Project Page

### ISSUE THREAD

**Issue by fu-sen** [benbalter/retlab#34]
### Describe the bug

Project Page `●●● .github.io/●●●` cannot display the image of the top page

### Steps to reproduce the behavior

When you publish it on Project Page `●●●.github.io/●●●`, you can check it immediately on the top page.

### Expected behavior

image.jpg is fixed in `/assets/css/style.css`.

[/assets/css/style.css](https://github.com/benbalter/retlab/blob/master/assets/css/style.css)
```
.hero-unit{background-image:url("/assets/img/header.jpg");background-size:cover;background-position:top left;height:400px}.
```

So for the project page `●●●.github.io/project/` , It is located at **/project**/assets/img/header.jpg

### Screenshots

I actually used it in Project Pages and ran into this issue:
![スクリーンショット 2020-12-06 14 32 51](https://user-images.githubusercontent.com/5434159/101272496-29dce600-37d0-11eb-8f0b-9784b82339d2.jpg)

**Comment by fu-sen** [comment]
I have implemented the following workaround:
[/assets/css/style.css](https://github.com/remotetheme/retlab/blob/main/assets/css/style.css)
```
.hero-unit{background-image:url(".../img/header.jpg");
```

It's working:
https://remotetheme.github.io/retlab/

**Comment by benbalter** [comment]
@fu-sen yes, that will work for pages that are `retlab/markdown.html`, but if you want page that are `retlab/markdown/` you'll need to include the absolute path to the image (either by hard-coding it or by making `style.css` a page and using `{{ absolute_url }}`.
