### ISSUE TITLE
codeblocks are washed out in dark mode

### ISSUE THREAD

**Issue by deargle** [benbalter/retlab#44]
Codeblocks in dark mode look washed out, like this:

![image](https://user-images.githubusercontent.com/1174653/139740559-bca83478-aea7-4ab6-a256-8bf3d6c522b7.png)

Because the github theme doesn't handle switching the codeblock background color to work for dark mode.

Here's a bandaid approach that works, idk if best practice though. I replaced `highlighting.scss` with media imports for two rougify styles that I added to the `/sass` directory: `base16.monokai.dark` and `github` 

```scss
# sass/_highlighting.scss
@media (prefers-color-scheme: dark) {
  @import 'base16.monokai.dark';
}

@media (prefers-color-scheme: light) {
  @import 'github';
}
```

**Comment by benbalter** [comment]
@deargle I didn't realize you could do that, but as of https://github.com/benbalter/retlab/commit/9df9c8bcbfcfc373a6cd113a661ee759a8cca63c, this has been fixed - thanks for the suggestion!
