### ISSUE TITLE
site.github.build_revision metadata not populating when site built on github pages

### ISSUE THREAD

**Issue by deargle** [benbalter/retlab#46]
I'm not sure how to chase this down yet, but `{{ site.github.build_revision }}` isn't populating at least for sites that use this theme (maybe all themes?) when my site is built on github, leading to empty `?v=` strings. 

This means that cache-busting isn't working.

It's happening on ben.balter.com, too. For example:
![image](https://user-images.githubusercontent.com/1174653/147326617-7ce38ef1-721b-467d-80d6-c385c6248a3b.png)

**Comment by deargle** [comment]
Probably this https://github.com/jekyll/github-metadata/issues/220

**Comment by benbalter** [comment]
I'm able to reproduce this behavior for Actions-based builds and flagged the behavior with the Pages team.

**Comment by benbalter** [comment]
Fix in progress via https://github.com/actions/jekyll-build-pages/pull/7.

**Comment by yoannchaudet** [comment]
And this is fixed now. Sorry for the inconvenience and thank you for catching this one!
